version: "3.5"

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-mdbloglite
    env_file:
      - ../env/.env
    volumes:
      - /opt/certbot/www/:/var/www/certbot/:rw
      - /opt/certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot-entrypoint.sh:/certbot-entrypoint.sh
    entrypoint: >
      sh -c /certbot-entrypoint.sh
