# Generated by Django 5.1.2 on 2024-10-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to='avatars'),
        ),
    ]
