version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mdblog
    container_name: blog
    env_file:
      - ./env/.env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/app/src/
    restart: always
    depends_on:
      - db
      - cache
    command: "bash ./scripts/entrypoint.sh"
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: blog_db
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:latest
    container_name: blog_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./env/.env
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
    name: backend
