version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mdblog_dev
    container_name: blog_dev
    env_file:
      - ./env/.env
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app/src/
    restart: always
    command: "bash ./scripts/entrypoint.sh"
    networks:
      - backend_dev
networks:
  backend_dev:
    driver: bridge
    name: backend_dev
