version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mdblog_dev
    container_name: blog_dev
    env_file:
      - ./env/.env
    ports:
      - 8000:8000
    depends_on:
      - cache
    volumes:
      - ./:/usr/app/src/
    restart: always
    command: "bash ./scripts/entrypoint.sh"
    networks:
      - backend_dev

  cache:
    image: redis:latest
    container_name: cache_dev
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./env/.env
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend_dev

  celery_worker:
    restart: always
    build: .
    image: celery_worker_dev
    container_name: celery_worker_dev
    volumes:
      - ./:/usr/app/src
    env_file:
      - ./env/.env
    depends_on:
      - cache
      - web
    command: 'celery -A config worker -l info'
    networks:
      - backend_dev

networks:
  backend_dev:
    driver: bridge
    name: backend_dev
