# This workflow will run on every push to the main branch
# and deploy the changes to the production server.
# Then web applicaton container restarts.
# UPD: If it is needed, the web container will be rebuilded.

name: Deploy changes to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      WEB_REBUILD_NEEDED: false
      NGINX_RESTART_NEEDED: false
    steps:
      - name: Check files conditions
        run: |
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          echo Changed files: $CHANGED_FILES

          if echo $CHANGED_FILES | grep -qE "requirements.txt|Dockerfile|docker-compose-production.yaml"; then
            echo "WEB_REBUILD_NEEDED=true" >> $GITHUB_ENV
          fi

          if echo $CHANGED_FILES | grep -qE ".*/nginx/secure.sh"; then
            echo ${{ secrets.SUDO }} | sudo -S ../src/nginx/secure.sh
            echo "NGINX_RESTART_NEEDED=true" >> $GITHUB_ENV
          fi
          
          echo Check is done
          echo WEB_REBUILD_NEEDED = ${{ env.WEB_REBUILD_NEEDED }}
          echo NGINX_RESTART_NEEDED = ${{ env.NGINX_RESTART_NEEDED }}

      - name: Pull changes
        run: |
          echo "Pull is starting"
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          git pull origin main
          echo "Pull is done"

      - name: Stop running web container
        run: |
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          cd src
          docker compose -f docker-compose-production.yaml stop web

      - name: Rebuild web container if it is needed
        if: ${{ env.WEB_REBUILD_NEEDED }} == 'true'
        run: |
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          cd src
          docker compose -f docker-compose-production.yaml up --build -d --no-deps web
      
      - name: Only restart web container if rebuild is not needed
        if: ${{ env.WEB_REBUILD_NEEDED }} == 'false'
        run: |
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          cd src
          docker compose -f docker-compose-production.yaml restart web

      - name: Restart nginx container if it needs
        if: ${{ env.NGINX_RESTART_NEEDED }} == 'true'
        run: docker restart nginx
